name: Build Node.js Image

on:
  pull_request:
    types: [labeled]
    labels: [check]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Node.js image
        run: echo "hi"
      - name: Remove check label
        uses: actions/github-script@v6
        with:
          script: |
            try {
              if (github.context && github.context.payload && github.context.payload.pull_request) {
                github.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  name: 'check'
                });
              }
            } catch (error) {
              core.warning(`Error removing label: ${error}`);
            }
