name: Build Node.js Image

on:
  pull_request:
    types: [labeled]
    labels: [check]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Node.js image
        run: code ../
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-remove-labels@v1
        if: ${{ startsWith(fail_on_error, '/remove-labels') }}
        with:
          labels: check
