name: CI/CD Pipeline

on:
  pull_request:
    types: [labeled]
    labels: [check]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check branch name format
        run: |
          if [[ "$(git rev-parse --abbrev-ref HEAD)" != "feature/"* ]]; then
            echo "Branch name must follow the format 'feature/xx'"
            exit 1
          fi
      - name: Build and run Docker image
        run: |
          ruby/docker/build_node_image.sh node
          # Assuming up_docker.sh handles error checking within the Docker container
          # and runs 'node index.js'
