name: Build Node.js Image

on:
  pull_request:
    types: [labeled]
    labels: [check]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Node.js image
        run: echo "hello world!"
